baseURL = 'https://ai.visualizing.jp/'
theme = 'hugo-theme-stack'
DefaultContentLanguage = "ja"
hasCJKLanguage = true

[languages]
  [languages.ja]
    languageName = "æ—¥æœ¬èªž"
    title = "AI Visualizing.JP"
    weight = 1

[params.sidebar]
    emoji = "ðŸ‘¾"
    subtitle = ""
    [params.sidebar.avatar]
        enabled = true
        local = true
        src = "img/avatar.png"
